/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/admin/schedules/import": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["import"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/sync/klid/intersections": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["syncIntersections"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/sync/tago/bus-route": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["syncBusRoute"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/boarding-attempts/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations["updateBoardingAttempt"];
    trace?: never;
  };
  "/api/v1/commute-routes": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list"];
    put?: never;
    post: operations["create_4"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/commute-routes/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["detail"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/commute-routes/{id}/calibration": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["calibration"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/commute-routes/{id}/legs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: operations["replaceLegs"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/commute-routes/{routeId}/recommendation": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["forTargetArrival"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/commute-routes/{routeId}/recommendation-history": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["recommendationHistory"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/commute-routes/{routeId}/recommendation/latest": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["latest"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/commute-trips": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["search"];
    put?: never;
    post: operations["create_3"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/commute-trips/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations["update"];
    trace?: never;
  };
  "/api/v1/commute-trips/{id}/boarding-attempts": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["upsertBoardingAttempt"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/commute-trips/{id}/gps-traces": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["tripTraces"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/gps-traces/batch": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["saveBatch"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/route-legs/{id}/signal-crossings": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: operations["replaceSignalCrossings"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/traffic-signals": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["create_2"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/traffic-signals/nearby": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["nearby_1"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/transit-lines": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["create_1"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/transit-lines/search": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["search_1"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/transit-lines/{lineId}/schedules/next": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["next"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/transit-stops": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/transit-stops/nearby": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["nearby"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    BoardingAttemptResponse: {
      /** Format: date-time */
      alightedAt?: string | null;
      /** Format: date-time */
      arrivedAtStopAt?: string | null;
      /** Format: int32 */
      attemptSeq: number;
      /** Format: date-time */
      createdAt: string;
      /** Format: int64 */
      id: number;
      notes?: string | null;
      /** @enum {string} */
      result: "CAUGHT" | "MISSED" | "UNKNOWN";
      /** Format: int64 */
      routeLegId: number;
      /** Format: int64 */
      tripId: number;
      /** Format: date-time */
      vehicleActualDepartureAt?: string | null;
      /** Format: date-time */
      vehicleScheduledOrPredictedAt?: string | null;
    };
    BusRouteSyncResponse: {
      cityCode: string;
      lineStops: components["schemas"]["SyncCountsResponse"];
      lines: components["schemas"]["SyncCountsResponse"];
      routeIds: string[];
      routeNo: string;
      stops: components["schemas"]["SyncCountsResponse"];
    };
    CommuteRouteDetailResponse: {
      legs: components["schemas"]["RouteLegResponse"][];
      route: components["schemas"]["CommuteRouteResponse"];
    };
    CommuteRouteResponse: {
      /** Format: date-time */
      createdAt: string;
      /** Format: double */
      destinationLat: number;
      /** Format: double */
      destinationLng: number;
      /** @enum {string} */
      direction: "TO_WORK" | "TO_HOME";
      /** Format: int64 */
      id: number;
      isActive: boolean;
      name: string;
      /** Format: double */
      originLat: number;
      /** Format: double */
      originLng: number;
    };
    CommuteTripResponse: {
      /** Format: date-time */
      arrivedDestinationAt?: string | null;
      boardingAttempts: components["schemas"]["BoardingAttemptResponse"][];
      /** Format: date-time */
      createdAt: string;
      /** Format: int64 */
      id: number;
      /** Format: date-time */
      leftHomeAt?: string | null;
      /** Format: int64 */
      routeId: number;
      /** Format: date */
      tripDate: string;
    };
    CreateCommuteRouteRequest: {
      /** Format: double */
      destinationLat: number;
      /** Format: double */
      destinationLng: number;
      /** @enum {string} */
      direction: "TO_WORK" | "TO_HOME";
      isActive: boolean;
      name: string;
      /** Format: double */
      originLat: number;
      /** Format: double */
      originLng: number;
    };
    CreateCommuteTripRequest: {
      /** Format: date-time */
      leftHomeAt?: string | null;
      /** Format: int64 */
      routeId: number;
      /** Format: date */
      tripDate: string;
    };
    CreateTrafficSignalRequest: {
      crsrdId?: string | null;
      description?: string | null;
      /** Format: double */
      lat: number;
      /** Format: double */
      lng: number;
      name?: string | null;
      stdgCd?: string | null;
    };
    CreateTransitLineRequest: {
      agency?: string | null;
      externalId?: string | null;
      hasRealtimeApi: boolean;
      /** @enum {string} */
      mode: "BUS" | "SUBWAY" | "GTX";
      name: string;
      stdgCd?: string | null;
    };
    CreateTransitStopRequest: {
      externalId?: string | null;
      /** Format: double */
      lat: number;
      /** Format: double */
      lng: number;
      /** @enum {string} */
      mode: "BUS" | "SUBWAY" | "GTX";
      name: string;
      stdgCd?: string | null;
    };
    DepartureRecommendationResponse: {
      /** Format: int32 */
      bufferSeconds: number;
      /** Format: double */
      catchProbability: number;
      /** Format: date-time */
      computedAt: string;
      modelVersion: string;
      /** Format: date-time */
      recommendedLeaveHomeAt: string;
      /** Format: date-time */
      targetArrivalAt: string;
    };
    GpsPointRequest: {
      /** Format: double */
      accuracyM?: number | null;
      /** Format: double */
      lat: number;
      /** Format: double */
      lng: number;
      /** Format: date-time */
      recordedAt: string;
      /** Format: double */
      speedMps?: number | null;
    };
    GpsTraceBatchRequest: {
      points: components["schemas"]["GpsPointRequest"][];
      /** Format: int64 */
      tripId?: number | null;
    };
    GpsTraceBatchResponse: {
      /** Format: int32 */
      accepted: number;
      /** Format: int32 */
      ignored: number;
    };
    GpsTraceResponse: {
      /** Format: double */
      accuracyM?: number | null;
      /** Format: double */
      lat: number;
      /** Format: double */
      lng: number;
      /** Format: date-time */
      recordedAt: string;
      /** Format: double */
      speedMps?: number | null;
    };
    IntersectionSyncResponse: {
      intersections: components["schemas"]["SyncCountsResponse"];
      stdgCd: string;
    };
    LegCalibrationResponse: {
      /** Format: int64 */
      alightStopId?: number | null;
      alightStopName?: string | null;
      /** Format: int64 */
      boardStopId?: number | null;
      boardStopName?: string | null;
      /** @enum {string} */
      legType: "WALK" | "TRANSIT";
      /** Format: double */
      plannedDistanceM?: number | null;
      /** Format: int32 */
      plannedTravelSec?: number | null;
      predictionRows: components["schemas"]["PredictionCalibrationRowResponse"][];
      /** Format: int64 */
      routeLegId: number;
      /** Format: int32 */
      seqOrder: number;
      /** Format: int64 */
      transitLineId?: number | null;
      transitLineName?: string | null;
      travelTimeRows: components["schemas"]["TravelTimeCalibrationRowResponse"][];
      walkingProfile?: components["schemas"]["WalkingProfileResponse"] | null;
    };
    NextDeparturesResponse: {
      departures: components["schemas"]["ScheduledDepartureResponse"][];
      directionCode: string;
      /** Format: int64 */
      stopId: number;
      /** Format: int64 */
      transitLineId: number;
    };
    PredictionCalibrationRowResponse: {
      /** Format: int32 */
      biasSec: number;
      /** @enum {string} */
      dayType: "WEEKDAY" | "SATURDAY" | "SUNDAY_HOLIDAY";
      /** Format: int32 */
      sampleCount: number;
      /** Format: int32 */
      stddevSec: number;
      timeBandEnd: string;
      timeBandStart: string;
      /** Format: date-time */
      updatedAt: string;
    };
    RecommendationHistoryDayResponse: {
      /** Format: date */
      date: string;
      recommendations: components["schemas"]["DepartureRecommendationResponse"][];
      trips: components["schemas"]["RecommendationHistoryTripResponse"][];
    };
    RecommendationHistoryTripResponse: {
      allLegsCaught: boolean;
      /** Format: date-time */
      arrivedDestinationAt?: string | null;
      /** Format: date-time */
      leftHomeAt?: string | null;
      /** Format: int32 */
      missedCount: number;
      /** Format: int64 */
      tripId: number;
    };
    ReplaceRouteLegsRequest: {
      legs: components["schemas"]["RouteLegRequest"][];
    };
    ReplaceSignalCrossingsRequest: {
      crossings: components["schemas"]["SignalCrossingRequest"][];
    };
    RouteCalibrationResponse: {
      globalWalkingProfile?: components["schemas"]["WalkingProfileResponse"] | null;
      legs: components["schemas"]["LegCalibrationResponse"][];
      /** Format: int32 */
      minSamples: number;
      /** Format: int64 */
      routeId: number;
    };
    RouteLegRequest: {
      /** Format: int64 */
      alightStopId?: number | null;
      /** Format: int64 */
      boardStopId?: number | null;
      /** Format: double */
      endLat?: number | null;
      /** Format: double */
      endLng?: number | null;
      /** Format: int64 */
      id?: number | null;
      /** @enum {string} */
      legType: "WALK" | "TRANSIT";
      /** Format: double */
      plannedDistanceM?: number | null;
      /** Format: int32 */
      plannedTravelSec?: number | null;
      /** Format: int32 */
      seqOrder: number;
      /** Format: double */
      startLat?: number | null;
      /** Format: double */
      startLng?: number | null;
      /** Format: int64 */
      transitLineId?: number | null;
    };
    RouteLegResponse: {
      alightStop?: components["schemas"]["TransitStopResponse"] | null;
      /** Format: int64 */
      alightStopId?: number | null;
      boardStop?: components["schemas"]["TransitStopResponse"] | null;
      /** Format: int64 */
      boardStopId?: number | null;
      /** Format: double */
      endLat?: number | null;
      /** Format: double */
      endLng?: number | null;
      /** Format: int64 */
      id: number;
      /** @enum {string} */
      legType: "WALK" | "TRANSIT";
      /** Format: double */
      plannedDistanceM?: number | null;
      /** Format: int32 */
      plannedTravelSec?: number | null;
      /** Format: int32 */
      seqOrder: number;
      signalCrossings: components["schemas"]["SignalCrossingResponse"][];
      /** Format: double */
      startLat?: number | null;
      /** Format: double */
      startLng?: number | null;
      transitLine?: components["schemas"]["TransitLineResponse"] | null;
      /** Format: int64 */
      transitLineId?: number | null;
    };
    ScheduledDepartureResponse: {
      /** @enum {string} */
      dayType: "WEEKDAY" | "SATURDAY" | "SUNDAY_HOLIDAY";
      /** Format: date-time */
      departureAt: string;
      scheduledTime: string;
      /** Format: date */
      serviceDate: string;
    };
    SignalCrossingRequest: {
      approachDir: string;
      /** Format: int32 */
      seqOrder: number;
      signalKind: string;
      /** Format: int64 */
      trafficSignalId: number;
    };
    SignalCrossingResponse: {
      approachDir: string;
      /** Format: int64 */
      id: number;
      /** Format: int32 */
      seqOrder: number;
      signalKind: string;
      /** Format: int64 */
      trafficSignalId: number;
    };
    SyncCountsResponse: {
      /** Format: int32 */
      created: number;
      /** Format: int32 */
      fetched: number;
      /** Format: int32 */
      skipped: number;
      /** Format: int32 */
      updated: number;
    };
    TrafficSignalResponse: {
      /** Format: date-time */
      createdAt: string;
      crsrdId?: string | null;
      description?: string | null;
      /** Format: double */
      distanceM?: number | null;
      /** Format: int64 */
      id: number;
      /** Format: double */
      lat: number;
      /** Format: double */
      lng: number;
      name?: string | null;
      stdgCd?: string | null;
    };
    TransitLineResponse: {
      agency?: string | null;
      /** Format: date-time */
      createdAt: string;
      externalId?: string | null;
      hasRealtimeApi: boolean;
      /** Format: int64 */
      id: number;
      /** @enum {string} */
      mode: "BUS" | "SUBWAY" | "GTX";
      name: string;
      stdgCd?: string | null;
    };
    TransitStopResponse: {
      /** Format: date-time */
      createdAt: string;
      /** Format: double */
      distanceM?: number | null;
      externalId?: string | null;
      /** Format: int64 */
      id: number;
      /** Format: double */
      lat: number;
      /** Format: double */
      lng: number;
      /** @enum {string} */
      mode: "BUS" | "SUBWAY" | "GTX";
      name: string;
      stdgCd?: string | null;
    };
    TravelTimeCalibrationRowResponse: {
      /** @enum {string} */
      dayType: "WEEKDAY" | "SATURDAY" | "SUNDAY_HOLIDAY";
      /** Format: int32 */
      meanSec: number;
      /** Format: int32 */
      sampleCount: number;
      /** Format: int32 */
      stddevSec: number;
      timeBandEnd: string;
      timeBandStart: string;
      /** Format: date-time */
      updatedAt: string;
    };
    UpdateBoardingAttemptRequest: {
      /** Format: date-time */
      alightedAt?: string | null;
      /** Format: date-time */
      arrivedAtStopAt?: string | null;
      notes?: string | null;
      /** @enum {string|null} */
      result?: "CAUGHT" | "MISSED" | "UNKNOWN" | null;
      /** Format: date-time */
      vehicleActualDepartureAt?: string | null;
      /** Format: date-time */
      vehicleScheduledOrPredictedAt?: string | null;
    };
    UpdateCommuteTripRequest: {
      /** Format: date-time */
      arrivedDestinationAt?: string | null;
      /** Format: date-time */
      leftHomeAt?: string | null;
    };
    UpsertBoardingAttemptRequest: {
      /** Format: date-time */
      alightedAt?: string | null;
      /** Format: date-time */
      arrivedAtStopAt?: string | null;
      /** Format: int32 */
      attemptSeq: number;
      notes?: string | null;
      /** @enum {string|null} */
      result?: "CAUGHT" | "MISSED" | "UNKNOWN" | null;
      /** Format: int64 */
      routeLegId: number;
      /** Format: date-time */
      vehicleActualDepartureAt?: string | null;
      /** Format: date-time */
      vehicleScheduledOrPredictedAt?: string | null;
    };
    WalkingProfileResponse: {
      /** Format: double */
      avgSpeedMps: number;
      /** Format: int32 */
      sampleCount: number;
      /** Format: double */
      stddevSpeedMps: number;
      /** Format: date-time */
      updatedAt: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  import: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        "multipart/form-data": {
          /** Format: binary */
          file: string;
        };
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["SyncCountsResponse"];
        };
      };
    };
  };
  syncIntersections: {
    parameters: {
      query: {
        stdgCd: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["IntersectionSyncResponse"];
        };
      };
    };
  };
  syncBusRoute: {
    parameters: {
      query: {
        cityCode: string;
        routeNo: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["BusRouteSyncResponse"];
        };
      };
    };
  };
  updateBoardingAttempt: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateBoardingAttemptRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["BoardingAttemptResponse"];
        };
      };
    };
  };
  list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["CommuteRouteResponse"][];
        };
      };
    };
  };
  create_4: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateCommuteRouteRequest"];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["CommuteRouteResponse"];
        };
      };
    };
  };
  detail: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["CommuteRouteDetailResponse"];
        };
      };
    };
  };
  calibration: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["RouteCalibrationResponse"];
        };
      };
    };
  };
  replaceLegs: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReplaceRouteLegsRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["CommuteRouteDetailResponse"];
        };
      };
    };
  };
  forTargetArrival: {
    parameters: {
      query: {
        targetArrivalAt: string;
      };
      header?: never;
      path: {
        routeId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["DepartureRecommendationResponse"];
        };
      };
    };
  };
  recommendationHistory: {
    parameters: {
      query: {
        from: string;
        to: string;
      };
      header?: never;
      path: {
        routeId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["RecommendationHistoryDayResponse"][];
        };
      };
    };
  };
  latest: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        routeId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["DepartureRecommendationResponse"];
        };
      };
    };
  };
  search: {
    parameters: {
      query?: {
        routeId?: number;
        from?: string;
        to?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["CommuteTripResponse"][];
        };
      };
    };
  };
  create_3: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateCommuteTripRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["CommuteTripResponse"];
        };
      };
    };
  };
  update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateCommuteTripRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["CommuteTripResponse"];
        };
      };
    };
  };
  upsertBoardingAttempt: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpsertBoardingAttemptRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["BoardingAttemptResponse"];
        };
      };
    };
  };
  tripTraces: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["GpsTraceResponse"][];
        };
      };
    };
  };
  saveBatch: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GpsTraceBatchRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["GpsTraceBatchResponse"];
        };
      };
    };
  };
  replaceSignalCrossings: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReplaceSignalCrossingsRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["RouteLegResponse"];
        };
      };
    };
  };
  create_2: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateTrafficSignalRequest"];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["TrafficSignalResponse"];
        };
      };
    };
  };
  nearby_1: {
    parameters: {
      query: {
        lat: number;
        lng: number;
        radiusM?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["TrafficSignalResponse"][];
        };
      };
    };
  };
  create_1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateTransitLineRequest"];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["TransitLineResponse"];
        };
      };
    };
  };
  search_1: {
    parameters: {
      query: {
        mode?: "BUS" | "SUBWAY" | "GTX";
        keyword: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["TransitLineResponse"][];
        };
      };
    };
  };
  next: {
    parameters: {
      query: {
        stopId: number;
        direction: string;
        at?: string;
        limit?: number;
      };
      header?: never;
      path: {
        lineId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["NextDeparturesResponse"];
        };
      };
    };
  };
  create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateTransitStopRequest"];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["TransitStopResponse"];
        };
      };
    };
  };
  nearby: {
    parameters: {
      query: {
        lat: number;
        lng: number;
        radiusM?: number;
        mode?: "BUS" | "SUBWAY" | "GTX";
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["TransitStopResponse"][];
        };
      };
    };
  };
}
